Capstone
eng-mohamed-eldeeb/capstone pull request #1
Opened 2022-02-10 21:36 UTC by eng-mohamed-eldeeb

Create a web page for the ICT event. the web page is almost identical to the given design. There are differences in images and in the paragraphs.  I improvised in the menu put it works perfectly.

The loom video: https://www.loom.com/share/9447a60975914abb9276c621b3ca0049

2022-02-10 22:45 UTC, enaburekhan reviewed
Hi Mohamed, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project with no descriptive readme. Kindly use this [template](https://github.com/microverseinc/readme-template/blob/master/README.md) as a starting point for your readme.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Code review by **Eric Enaburekhan**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-02-11 08:46 UTC, oloomoses requested changes
Hi @eng-mohamed-eldeeb, 

**Highlights** 
- Great job on the UI and PR :heavy_check_mark: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-11 08:46 UTC, oloomoses commented on README.md
> +
- [x] To make your readme more descriptive, Kindly add the project description and instructions on how to set up and run the project locally.
- [x] Kindly ensure that the project is deployed and the live link is added in the readme file. You can use GitHub pages as per the project's requirements.

2022-02-11 08:46 UTC, oloomoses commented on index.html
> +              Consequatur assumenda illo accusamus molestiae accusantium fugit,
- [x] `home` and `about` pages should be different pages. Kindly implement each page on its own so that when a user clicks on the `home` page they will only see the content of that page, and the same for `about` page.

2022-02-11 08:46 UTC, oloomoses commented on index.html
> +        </div>
- [x] The cards on the `featured section` do not have a background color. Kindly remove the background from your design and also the scroll on the mobile view.
- [x] Kindly compare the screenshots below and make the necessary adjustments, including fonts, layout, and colors.

**Your Design**
![Screenshot from 2022-02-11 11-22-22](https://user-images.githubusercontent.com/20245164/153558775-23ba34a1-42c7-4bb5-860f-9ffa8994906b.png)

**Given Design**
![Screenshot from 2022-02-11 11-17-40](https://user-images.githubusercontent.com/20245164/153558886-1daf7255-50a1-4fe0-8d55-d884668787ed.png)

2022-02-11 15:21 UTC, Amrhub approved these changes
# Approved 💯 ✅ 🥳 🎈 🎉 

Hi @eng-mohamed-eldeeb, 👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-11 15:27 UTC, merged